.github/workflows/pr-builder.yml

This pull request introduces a new GitHub Actions workflow to automate building and testing the project on pull requests. The workflow is designed to streamline the development process by ensuring consistent testing and building across contributions.
* [`.github/workflows/pr-builder.yml`](diffhunk://#diff-5274abb9a1f90be1adf589d21c49758b213e3aac969ac7335bfe26b7963a348eR1-R44): Added a new workflow named "PR Builder" that triggers on pull requests to the `main` branch or via manual dispatch. It sets up the Go environment, caches Go modules, installs dependencies, and runs `make all` to build and test the project.

Add PR builder to automate building and testing the project on pull requests

---

internal/system/cache/basecache.go

This pull request introduces caching functionality defining a base cache and related operations.
* [`internal/system/cache/basecache.go`](diffhunk://#diff-6ead129ecfa4f8b01cf7fe27eb01f587a4b5af8e06bc9243a3cb18adc76bdcffR1-R104): Added `BaseCache`, a thread-safe in-memory caching system with support for adding, retrieving, and clearing cache entries. Includes expiration handling for cache entries.

Add base cache implementation

---

README.md

Update readme curl command

---

README.md
backend/cmd/server/main.go
frontend/loginportal/src/components/LoginPage.js
frontend/loginportal/src/components/OAuth2ErrorPage.js

Rename thunder terms

---

backend/internal/application/handler/applicationhandler.go
backend/internal/system/services/applicationservice.go
docs/apis/application.yaml

This pull request adds detailed API documentation and updates the routes for the application management system. The changes include adding Swagger annotations to handler methods, fixing route definitions, and introducing a new OpenAPI YAML file to describe the API.
* Added Swagger annotations to all handler methods in `backend/internal/application/handler/applicationhandler.go`, providing summaries, descriptions, tags, parameters, responses, and security definitions for each endpoint. [[1]](diffhunk://#diff-0c4208f893f204ecdbc8787bceb345a8db8fd9dafaf7cf6bf72a04e4a5506f7aR31-R41) [[2]](diffhunk://#diff-0c4208f893f204ecdbc8787bceb345a8db8fd9dafaf7cf6bf72a04e4a5506f7aR56-R66) [[3]](diffhunk://#diff-0c4208f893f204ecdbc8787bceb345a8db8fd9dafaf7cf6bf72a04e4a5506f7aR100-R109) …

Add annotations and generate swagger for application api

---

backend/internal/application/model/oauthapp.go

$subject to reflect more meaningful naming. Also this PR fixes function comment to reflect the proper function name.

Rename model.go to oauthapp.go

---

README.md

This pull request updates the `README.md` file to include detailed instructions for setting up and running the application with a PostgreSQL database. The changes provide a clear, step-by-step guide for configuring the database and updating the application's configuration.
* **New PostgreSQL Setup Instructions**: Added detailed steps to create and initialize two PostgreSQL databases (`thunderdb` and `runtimedb`) using Docker, including commands for creating the databases and populating them with required data.
* **Configuration Update**: Included instructions to modify the `deployment.yaml` file to configure the application to use the PostgreSQL databases, specifying connection details like hostname, port, database names, and credentials.

Add instructions to run with postgres db and remove the section on running dev env

---

backend/internal/oauth/oauth2/authz/authzhandler.go
backend/internal/oauth/oauth2/authz/authzvalidator.go
backend/internal/oauth/oauth2/token/tokenhandler.go
backend/internal/oauth/oauth2/utils/oauthutils.go
backend/internal/oauth/session/store/sessiondatastore.go
backend/internal/system/cache/basecache.go
backend/internal/system/log/log.go
backend/internal/system/managers/servicemanager.go
backend/internal/system/services/authorizationservice.go
backend/internal/system/utils/httputil.go

This pull request introduces significant refactoring and enhancements to the codebase. The changes focus on improving code readability, modularity, and adherence to best practices by introducing interfaces, standardizing method signatures, and replacing redundant code. Additionally, the request and response writer variables have been consistently renamed across the codebase for clarity.

Formatting and best practices

---

backend/cmd/server/repository/conf/deployment.yaml
backend/internal/oauth/jwt/jwtgenerator.go
backend/internal/oauth/oauth2/granthandlers/authorizationcode.go
backend/internal/oauth/oauth2/granthandlers/clientcredentials.go
backend/internal/system/config/config.go
samples/apps/oauth-client-app/src/App.css
samples/apps/oauth-client-app/src/components/HomePage.js
samples/apps/oauth-client-app/src/services/jwtService.js

This pull request introduces several enhancements and updates across the backend and frontend, focusing on improving JWT handling, OAuth configuration, and UI features for better usability and maintainability.
* Added support for OAuth JWT configuration in `deployment.yaml`, including `issuer` and `validity_period` fields.
* Introduced new `JWTConfig` and `OAuthConfig` structs in `config.go` to manage JWT and OAuth settings.
* Updated the `GenerateJWT` function in `jwtgenerator.go` to accept `sub` and `aud` parameters, calculate expiration time dynamically, and generate a unique `jti` using UUIDs. [[1]](diffhunk://#diff-fb7a2c9bb459d057dd0ad04b8521743961f170a6463ebdd8d402d0359f1d48e1L87-R94) [[2]](diffhunk://#diff-fb7a2c9bb459d057dd0ad04b8521743961f170a6463ebdd8d402d0359f1d48e1R105-R120) …

Improve the jwt token generation and sample app token display

---

backend/internal/application/model/oauthapp.go
backend/internal/application/service/applicationservice.go
backend/internal/oauth/oauth2/authz/authzhandler.go
backend/internal/oauth/oauth2/authz/authzvalidator.go
backend/internal/oauth/oauth2/constants/constants.go
backend/internal/oauth/oauth2/granthandlers/authorizationcode.go
backend/internal/oauth/oauth2/granthandlers/clientcredentials.go
backend/internal/oauth/oauth2/token/tokenhandler.go
backend/internal/oauth/oauth2/utils/oauthutils.go
backend/internal/system/utils/httputil.go
frontend/loginportal/src/components/LoginPage.js

This pull request introduces several improvements and fixes across the OAuth2 authorization code flow, validation logic, and error handling. The most significant changes include enhancing redirect URI validation, refactoring the authorization request validation, improving error handling in the token generation process, and adding utilities for validating error parameters. These updates aim to improve security, compliance with OAuth2 specifications, and overall code maintainability.

Add validations for the auth code flow

---

backend/cmd/server/repository/conf/deployment.yaml
backend/internal/authn/authnhandler.go
backend/internal/authn/model/model.go
backend/internal/authn/utils/authnutils.go
backend/internal/oauth/oauth2/authz/authzhandler.go
backend/internal/oauth/oauth2/authz/utils/authzutils.go
backend/internal/oauth/oauth2/token/tokenhandler.go
backend/internal/oauth/oauth2/utils/oauthutils.go
backend/internal/oauth/session/utils/sessionutils.go
backend/internal/outboundauth/abstract/abstractauthenticator.go
backend/internal/outboundauth/authenticator.go
backend/internal/outboundauth/basicauth/basicauthenticator.go
backend/internal/outboundauth/model/model.go
backend/internal/system/config/config.go
backend/internal/system/services/authnservice.go
backend/internal/system/utils/httputil.go
backend/internal/system/utils/serverutils.go

This pull request introduces a new authentication framework with support for pluggable authenticators, starting with a Basic Authenticator implementation. The changes include updates to the configuration, session management, and OAuth authorization flow to integrate the new framework.
* **New `AuthenticationHandler` and Authentication Flow**:
- Added `AuthenticationHandler` in `backend/internal/authn/authnhandler.go` to manage authentication requests and delegate them to the appropriate authenticator.
- Introduced `AuthenticationContext` and `AuthenticatedUser` data structures in `backend/internal/authn/model/model.go` to represent authentication context and user details. 
* **Authenticator Interface and Basic Authenticator**:
- Defined a pluggable `AuthenticatorInterface` in …

Add authenticator model and refactor authn service

---

package.json

This pull request updates the `package.json` file to enhance the development workflow by modifying and adding script commands.
* Modified the `start` script to include a `pnpm i` step before running `make run`, ensuring dependencies are installed before starting the application.
* Added a new `run` script as an alias for `make run`, providing a simpler way to execute the `make run` command.

Avoid the need to install packages separately from pnpm start

---

build.sh
samples/apps/oauth/.gitignore

This pull request introduces changes to enhance the build process for the Go backend and updates the `.gitignore` file for the OAuth sample app. The most notable updates include the addition of environment variables for cross-compilation and improved build flags for embedding metadata.

Update go build command to have OS and version flags

---

backend/go.mod
backend/internal/application/service/applicationservice.go
backend/internal/oauth/jwt/jwtgenerator.go
backend/internal/oauth/oauth2/authz/utils/authzutils.go
backend/internal/system/utils/uuidutil.go
backend/internal/user/service/userservice.go

This pull request introduces a new utility function, `GenerateUUID`, to replace the use of `github.com/google/uuid` across the codebase. 
* Added a new function `GenerateUUID` in `backend/internal/system/utils/uuidutil.go`. 
* Replaced `uuid.New().String()` with `utils.GenerateUUID()`.
* Replaced imports of `github.com/google/uuid` with `github.com/asgardeo/thunder/internal/system/utils` across multiple files.
The [ Authorization Code Flow](https://github.com/asgardeo/thunder?tab=readme-ov-file#2%EF%B8%8F%E2%83%A3-try-out-authorization-code-flow) was tested with the updated UUID generator.
https://github.com/user-attachments/assets/aca6708c-0cb4-4f8e-acb6-78f7d268d6f1
- https://github.com/asgardeo/thunder/issues/49

Introduce GenerateUUID utility and replace google/uuid usage

---

.github/workflows/release.yml

Update release description to include README introduction and license

---

README.md

This pull request updates the `README.md` file to refine the feature list and improve clarity. The most notable changes include reorganizing the authentication and API-related features for better readability.
Documentation updates:
* Replaced "OAuth 2.1" with "OAuth 2" and specified supported flows: "Authorization Code" and "Client Credentials."
* Consolidated login options under a single feature, specifying "Basic Authentication" and "Login with GitHub."
* Expanded the description of RESTful APIs to include "User Management" and "Application Management."

Update readme to reflect current capabilities

---

docs/apis/application.yaml
docs/apis/idp.yaml
docs/apis/user.yaml

This pull request updates the API specifications for `application`, `identity provider`, and `user` endpoints to migrate from Swagger 2.0 to OpenAPI 3.0.3. The changes include updating the schema definitions, replacing `definitions` with `components`, and adopting OpenAPI 3.0 features like `requestBody` and `content` for improved API documentation and consistency.
* Replaced `swagger: "2.0"` with `openapi: 3.0.3` and migrated `definitions` to `components.schemas` in all API files (`docs/apis/application.yaml`, `docs/apis/idp.yaml`, `docs/apis/user.yaml`). [[1]](diffhunk://#diff-f102b802beb28e9c82e8523b10aebc5e3be735469a491538c6635cdf6b1d9e55L1-L9) [[2]](diffhunk://#diff-437a109c090cc79be26ab1c04a4dd3033378a1f8fcf025725ffb587b8647f2d9L1-R5) …

Convert the api definitions from swagger 2 to OAS 3

---

backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/outboundauth/basicauth/basicauthenticator.go
backend/internal/system/log/log.go
backend/internal/user/service/userservice.go
backend/internal/user/store/constants.go
backend/internal/user/store/store.go

This pull request refactors the authentication logic for Basic Authentication by introducing a centralized user authentication mechanism. It replaces hardcoded user credentials with a dynamic user service, improving maintainability and scalability. Key changes include the addition of new methods for user identification and verification, integration of these methods into the authentication flow, and updates to database queries to support the new functionality.
* **Centralized User Authentication**:
- Introduced `getAuthenticatedUser` function in both `basicauthexecutor.go` and `basicauthenticator.go` to handle user authentication dynamically using the `UserService` interface. This replaces the previous hardcoded username/password checks. …

Introduce Identify & Verify functions to user service and integrate those with basic executor & authenticator

---

README.md

This pull request updates the `README.md` file to reflect changes in supported features, streamline the quickstart instructions, and improve consistency in cURL commands. The most important changes include removing the Authorization Code flow, updating RESTful API features, and standardizing cURL commands for better usability.
* Removed the Authorization Code flow from the list of supported OAuth 2.0/OpenID Connect (OIDC) features.
* Updated RESTful API features to include "App Native Login" and "Identity Provider Management."
* Simplified the quickstart instructions by removing redundant prerequisites and updating the example version numbers in the unzip commands.
* Removed the section detailing the Authorization Code flow, simplifying the authentication flow documentation.
* …

Update curl commands & content in readme to reflect latest changes

---

README.md
backend/cmd/server/repository/resources/graphs/auth_flow_config_google.json
backend/internal/executor/authassert/authassertexecutor.go
backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/executor/githubauth/githubauthexecutor.go
backend/internal/executor/googleauth/constants.go
backend/internal/executor/googleauth/googleauthexecutor.go
backend/internal/executor/oidcauth/model/model.go
backend/internal/executor/oidcauth/oidcauthexecutor.go
backend/internal/flow/constants/constants.go
backend/internal/flow/model/flowmodel.go
backend/internal/flow/utils/utils.go
backend/internal/oauth/jwt/jwtgenerator.go
backend/internal/oauth/oauth2/granthandlers/authorizationcode.go
backend/internal/oauth/oauth2/granthandlers/clientcredentials.go
backend/internal/system/crypto/jwt/utils/jwtutils.go
backend/internal/system/utils/stringutil.go
samples/apps/oauth/src/pages/LoginPage.tsx

This pull request introduces the Google OIDC auth executor along with some enhancements to the authentication flow configurations, refactors user authentication handling, improves OIDC executor functionality, and updates JWT generation to support custom claims. Below are the most important changes grouped by theme:
* Added the Google OIDC auth executor implementation enabling login with Google.
* Added a new Google authentication flow configuration in `auth_flow_config_google.json`, defining nodes and edges for Google OAuth2 authentication.
* Added support for JWKs endpoint in `OIDCExecProperties` and corresponding methods in `OIDCAuthExecutor`.
* Implemented methods for validating and extracting claims from ID tokens in `OIDCAuthExecutor`.
* Modified `GenerateJWT` to accept custom …

Add Google OIDC auth executor (with ID token verification utils)

---

samples/apps/oauth/package-lock.json
samples/apps/oauth/package.json
samples/apps/oauth/src/App.tsx
samples/apps/oauth/src/components/Layout.tsx
samples/apps/oauth/src/contexts/AuthContext.ts
samples/apps/oauth/src/contexts/AuthProvider.tsx
samples/apps/oauth/src/hooks/useAuth.ts
samples/apps/oauth/src/pages/HomePage.tsx
samples/apps/oauth/src/pages/LoginPage.tsx
samples/apps/oauth/src/pages/RedirectLoginPage.tsx
samples/apps/oauth/src/services/jwtService.ts
samples/apps/oauth/tsconfig.json

Fixed double submit on social login + password show/hide

---

build.sh

Modify build script to use a single certificate for both server and sample app

---

README.md

Update readme with foldable sections

---

build.sh

This pull request updates the `build.sh` script to enhance database initialization logic by introducing an override parameter, improving flexibility and control during the build process. The changes include modifications to how existing databases are handled and the addition of database initialization in the `run()` function.
During run databases will not be re-created by default and should remove existing to allow recreating.
During build databases will be recreated even it already exists.

Fix build script to recreate databases conditionally

---

samples/apps/oauth/src/pages/LoginPage.tsx

Add progress loader animation to the sample login page

---

backend/cmd/server/repository/resources/graphs/auth_flow_config_basic.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_github.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_google.json
backend/internal/flow/model/node.go
backend/internal/flow/model/taskexecutionnode.go
backend/internal/flow/utils/utils.go

This pull request refactors the node model and its related components in the backend flow system. The changes introduce a more structured approach to node types by replacing string-based types with a strongly-typed `NodeType`. Additionally, a new `TaskExecutionNode` implementation is added to handle task execution logic separately. These updates improve type safety, modularity, and error handling across the flow system.

Refactor node type implementation

---

.github/workflows/pr-builder.yml
tests/integration/main.go
tests/integration/testutils/testutils.go

Fix PR builder

---

backend/internal/flow/flowservice.go

This pull request refactors the `FlowService` in `backend/internal/flow/flowservice.go` to improve code clarity and modularity by splitting the `loadContext` method into two separate methods (`loadNewContext` and `loadPrevContext`) and introducing utility functions for flow handling. Additionally, it reorders and reintegrates some helper functions for better organization.
* Replaced the single `loadContext` method with `loadNewContext` and `loadPrevContext` to handle new and existing flows separately, improving code readability and maintainability. (`[[1]](diffhunk://#diff-12c944fec32bfea8c1b30556050bd0f49b28d9fe565a6029681bb5e656fad2d6L83-R93)`, `[[2]](diffhunk://#diff-12c944fec32bfea8c1b30556050bd0f49b28d9fe565a6029681bb5e656fad2d6R170-R181)`)
* Introduced the `isNewFlow` utility …

Refactor Execute function to reflect the core logic

---

backend/internal/flow/dao/flowdao.go
backend/internal/flow/flowservice.go

This pull request refactors the flow context management in the `FlowService` by delegating storage responsibilities to the `FlowDAO`. The changes improve separation of concerns and centralize context storage logic. Key updates include adding context management methods to `FlowDAO`, removing redundant fields and logic from `FlowService`, and updating methods in `FlowService` to use the new `FlowDAO` context management.

Refactor flow service by moving storage responsibility to DAO

---

README.md
backend/internal/executor/oauth/oauthexecutor.go
backend/internal/flow/constants/constants.go
backend/internal/flow/engine/flowengine.go
backend/internal/flow/handler/flowexechandler.go
backend/internal/flow/model/executor.go
backend/internal/flow/model/flowmodel.go
backend/internal/flow/model/node.go
backend/internal/flow/model/taskexecutionnode.go
backend/internal/system/services/flowexecutionservice.go
docs/apis/flow.yaml
samples/apps/oauth/src/pages/LoginPage.tsx
samples/apps/oauth/src/services/authService.ts

This pull request introduces multiple changes to improve the flow execution API and its associated components. The updates include renaming the API endpoint, restructuring response data to use a unified `FlowData` object, and updating documentation and sample code accordingly. These changes aim to enhance clarity, maintainability, and consistency across the codebase.
**Proposed response schema:**
```json
{
"flowId": "2c6d4c45-3de9-4a70-ae6b-ba1d034af6bc",
"flowStatus": "PROMPT_ONLY",
"type": "VIEW",
"data": {
"inputs": [
{
"name": "username",
"type": "string",
"required": true
}
],
"redirectURL": "https://example.com/redirect",
"additionalData": {
"idpName": "<idp_name>"
},
},
"assertion": "<jwt_token>"
}
```
* Renamed the flow execution API endpoint from `/flow/execution` to …

Update the flow execution API path and response schema

---

samples/apps/oauth/index.html

Rename sample app title

---

README.md
backend/cmd/server/repository/resources/graphs/auth_flow_config_sms.json
backend/internal/executor/authassert/authassertexecutor.go
backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/executor/oauth/oauthexecutor.go
backend/internal/executor/oidcauth/oidcauthexecutor.go
backend/internal/executor/smsauth/smsauthexecutor.go
backend/internal/flow/engine/flowengine.go
backend/internal/flow/jsonmodel/model.go
backend/internal/flow/model/executor.go
backend/internal/flow/model/flowmodel.go
backend/internal/flow/utils/utils.go
backend/internal/notification/message/constants/errorconstants.go
backend/internal/notification/message/model/model.go
backend/internal/notification/message/provider/provider.go
backend/internal/notification/message/service/clientservice.go
backend/internal/notification/message/service/notificationservice.go

This pull request introduces support for configuring authentication with SMS OTP allowing users to login into their applications using a OTP code send to the configured mobile number.
* Added `RuntimeData` to `EngineContext` and `NodeContext` in `flowmodel.go` to allow runtime data sharing across different stages of the nodes.
* Updated `FlowEngine` in `flowengine.go` to handle `RuntimeData` by merging it into the engine context when processing node responses.
* Introduced `Prerequisites` for executors in `executor.go`, allowing them to validate required conditions before execution.
* Introduced a new client service to the message notification module to retrieve message sender by name.
* Added a new graph configuration `auth_flow_config_sms.json` to define an SMS-based authentication …

Add the SMS OTP Auth Executor

---

backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_google_github_sms.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_sms.json
samples/apps/oauth/src/components/ConnectionErrorModal.tsx
samples/apps/oauth/src/pages/LoginPage.tsx
samples/apps/oauth/src/services/authService.ts

This pull request improves the sample application by introducing a new multi-method authentication flow configuration, updating the retry logic in the `ConnectionErrorModal` component, and modifying to the native authentication service to support new input types.
* Added a new JSON configuration file (`auth_flow_config_basic_google_github_sms.json`) to define a multi-method authentication flow supporting basic authentication, Google OAuth, GitHub OAuth, and SMS OTP.
* Updated the SMS-based authentication flow configuration to align with the new node naming convention (`mobile_prompt_username`).
* Refactored the `NativeAuthSubmitType` enum to replace `BASIC` with a more generic `INPUT` type and added support for `OTP` authentication.
* Updated the `submitNativeAuth` function to handle the …

Improve the Sample app to support SMS OTP and Dynamic Inputs

---

backend/internal/executor/attributecollect/attributecollector.go
backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/flow/constants/errorconstants.go
backend/internal/flow/flowservice.go
backend/internal/flow/model/executor.go
backend/internal/flow/utils/utils.go

This pull request introduces a new executor named attribute collector which can collect user attributes in login flows and update the profile. Additionally several changes to enhance the user attribute handling and improvement to check runtime data is added to support the a new executor.. Below is a summary of the most important changes.
* Added support for the `AttributeCollector` executor by importing the relevant package, updating `getExecutorConfigByName`, and adding a case in `GetExecutorByName` to instantiate the new executor.
* Modified `CheckInputData` in `executor.go` to consider both `UserInputData` and `RuntimeData` when determining if required data is missing.
* Updated `appendRequiredData` in `executor.go` to skip adding input data to the required list if it is already …

Add the AttributeCollector (executor) implementation

---

backend/internal/executor/attributecollect/attributecollector.go
backend/internal/executor/authassert/authassertexecutor.go
backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/executor/githubauth/githubauthexecutor.go
backend/internal/executor/googleauth/googleauthexecutor.go
backend/internal/executor/oauth/oauthexecutor.go
backend/internal/executor/oidcauth/oidcauthexecutor.go
backend/internal/executor/smsauth/smsauthexecutor.go
backend/internal/flow/engine/flowengine.go
backend/internal/flow/flowservice.go
backend/internal/flow/model/decisionnode.go
backend/internal/flow/model/promptnode.go
backend/internal/flow/model/taskexecutionnode.go
backend/internal/outboundauth/github/githubauthenticator.go
docs/content/customize-auth-flow.md

This pull request introduces updates to the handling of authenticated user attributes and runtime data across various authentication and flow processing components. Additionally, it standardizes the default UserID placeholder used in federated scenarios. The changes aim to enhance attribute management and improve consistency in user-related data handling.
Additionally this PR adds the auth flow customization guide.

Fix attribute collector with federated flows and update docs

---

samples/apps/oauth/src/pages/LoginPage.tsx

This pull request introduces an effect to automatically focus on OTP input fields and also refines the authentication response  handling to properly handle errors.
* Added a `useEffect` hook to automatically focus on the first OTP input field when it becomes available, improving usability for users entering one-time passwords.
* Refactored the `processAuthResponse` function to handle error states more clearly, including setting error messages and halting further processing when an error occurs. This ensures a more robust and user-friendly error-handling flow.

Improve the sample application

---

tests/integration/testutils/testutils.go

Fix zip file resolving logic for integration tests

---

samples/apps/oauth/package-lock.json
samples/apps/oauth/package.json
samples/apps/oauth/server/package-lock.json
samples/apps/oauth/server/package.json

Bump sample app version

---

.github/workflows/release.yml

Update release workflow to bump sample app version

---

README.md
backend/cmd/server/repository/conf/deployment.yaml
backend/internal/authn/constants/constants.go
backend/internal/authn/utils/authnutils.go
backend/internal/oauth/oauth2/constants/constants.go
backend/internal/outboundauth/basicauth/basicauthenticator.go
backend/internal/system/config/config.go
backend/internal/system/config/config_test.go
backend/tests/resources/deployment.yaml
frontend/apps/gate/src/app/error/page.tsx

This PR improves the authorization code flow to support a configurable gate client for user login frontend. Additionally this updates README with the auth code flow try out steps.

Fix authorization code flow with a configurable gate client

---

backend/internal/system/database/client/dbclient.go

\
This pull request includes a small but important change to the `Query` method in the `DBClient` implementation. The change ensures that any errors encountered during row iteration are properly checked and returned to the caller.
* [`backend/internal/system/database/client/dbclient.go`](diffhunk://#diff-848200784aa14c671eb132579fae6350a6d79894b8eef5c7d7be69f373eb2754R99-R102): Added a check for `rows.Err()` after iterating through query results to handle potential errors during row iteration.

Fix db query error handling

---

backend/internal/group/constants/errorconstants.go
backend/internal/group/model/group.go
backend/internal/group/service/groupservice.go
backend/internal/group/store/store.go

This pull request includes several changes to improve code clarity and maintainability by removing unused error constants, refactoring conditional logic, and enhancing variable naming for better readability.
* Removed the unused `ErrorInvalidRequest` constant from `errorconstants.go`.
* Removed the unused `ErrCannotDeleteGroupWithChildren` and `ErrInvalidRequest` constants from `group.go`.
* Replaced `if-else` conditional logic with a `switch` statement in the `resolveOU` method for better readability and scalability. [[1]](diffhunk://#diff-c968c9fcf81977db22a427b042701414eb10548b606387f7e16ecf05adc6e706L318-R319) [[2]](diffhunk://#diff-c968c9fcf81977db22a427b042701414eb10548b606387f7e16ecf05adc6e706L329-R330)
* Renamed the variable `pgid` to `parentGroupID` in `store.go` for clearer and …

Minor refactoring

---

backend/internal/flow/dao/flowdao.go

This pull request includes minor logging level adjustments in the `FlowDAO` initialization process. The changes replace `Info` logging with `Debug` logging to reduce logs at product startup

Cleaning up startup logs

---

backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_google_github_sms.json
backend/internal/executor/smsauth/smsauthexecutor.go
backend/internal/flow/model/executor.go
samples/apps/oauth/src/pages/LoginPage.tsx

This pull request introduces several changes to improve the handling of authentication flows, input data processing, and UI adjustments. The most significant updates include modifications to the authentication flow configuration, enhancements to data handling in the backend, and adjustments to the login page UI and functionality.
* Updated `auth_flow_config_basic_google_github_sms.json` to collect firstname, lastname and username attributes during basic and sms otp flows.
* Updated `smsauthexecutor.go` to conditionally include optional attributes (`email`, `firstName`, `lastName`) in the authenticated user object only if they are non-empty.
* Modified `executor.go` to ensure all input data is marked as required, simplifying the logic for appending required data.
* Enhanced `LoginPage.tsx` …

Update flow input data handling

---

backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_google_github_sms.json
backend/cmd/server/repository/resources/graphs/registration_flow_config_basic_google_github_sms.json
backend/internal/executor/smsauth/smsauthexecutor.go

- Fixes the SMS auth executor to get user id from context and skip user identification when the user is already authenticated. This fixes the authentication failure when the mobile number is prompted from the user during the auth flow.
- Add the customized all option registration flow graph

Fix SMS auth flow and add all option registration graph

---

README.md

Update readme with refresh token docs

---

build.sh

This pull request makes improvements to the `build.sh` script, including adding debug output and fixing an environment variable typo in the backend build function.

Fix build script for the go env variables

---

docs/apis/ou.yaml

This pull request enhances the error documentation in the `docs/apis/ou.yaml` file by adding detailed examples for various error scenarios, improving clarity and consistency, and updating the data type for error codes. The most important changes are grouped below:
* Added detailed examples for error scenarios such as invalid requests, parent organization unit not found, circular dependencies, and name conflicts under multiple HTTP status codes (`400`, `404`, `409`) to improve API documentation clarity. [[1]](diffhunk://#diff-e36ca15f70fb14f6ea92bfffc234f4937f72dfbc23f3e0fc05fac0d4cb9b84a1R103-R131) [[2]](diffhunk://#diff-e36ca15f70fb14f6ea92bfffc234f4937f72dfbc23f3e0fc05fac0d4cb9b84a1R229-R267) [[3]](diffhunk://#diff-e36ca15f70fb14f6ea92bfffc234f4937f72dfbc23f3e0fc05fac0d4cb9b84a1L244-R307 …

Update error codes in ou api

---

samples/apps/oauth/src/pages/LoginPage.tsx

This pull request introduces updates to the `LoginPage` component in `samples/apps/oauth/src/pages/LoginPage.tsx` to improve user input handling and error management during the authentication flow. The changes include resetting input states, detecting mobile number inputs, and conditionally processing authentication responses based on input type.

Fix sample app for mobile input

---

README.md
backend/cmd/server/repository/resources/graphs/auth_flow_config_basic.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_google.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_google_github.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_google_github_sms.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_github.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_google.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_sms.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_sms_with_username.json
backend/cmd/server/repository/resources/graphs/registration_flow_config_basic.json
backend/cmd/server/repository/resources/graphs/registration_flow_config_basic_google_github.json
backend/cmd/server/repository/resources/graphs/registration_flow_config_basic_google_github_sms.json
backend/cmd/server/repository/resources/graphs/registration_flow_config_sms.json
backend/internal/executor/googleauth/googleauthexecutor.go
docs/apis/flow.yaml
tests/integration/flowregistration/smsregistration_test.go
tests/integration/resources/deployment.yaml

- Remove redundant inputs from flow graph definitions which are already defined as default inputs in the individual executor level.
- Update default user in the README and test resources to avoid browser password warning

Cleanup flow definitions and update default user

---

docs/apis/group.yaml
docs/apis/ou.yaml
docs/apis/user.yaml

This pull request introduces enhancements to the `Organization-Units`, `Groups`, `Users` APIs, adding support to perform management operations using hierarchical organization unit handle paths. Key changes include new API endpoints, updated components, and additional query parameters for pagination.
* Improved `GET /organization-units`, `GET /groups` & `GET /users` endpoints to support pagination with the improved response structure, and the ability to provide the `limit`, `offset` params in the request.
* Added of new endpoints to retrieve sub resources that needs pagination. Ex: `GET /organization-units/{id}/ous`, `GET /organization-units/{id}/users`, `GET /organization-units/{id}/groups` `GET /groups/{id}/members`
* Introduced new endpoints with tags  `organization-units-by-path`, …

Improve organization-unit, group, user APIs

---

backend/internal/ou/constants/errorconstants.go
backend/internal/ou/handler/ouhandler.go
backend/internal/ou/model/ou.go
backend/internal/ou/service/ouservice.go
backend/internal/ou/store/queries.go
backend/internal/ou/store/store.go
tests/integration/ou/model.go
tests/integration/ou/ouapi_test.go

This pull request introduces pagination support for listing organization units, along with validation for pagination parameters and corresponding error handling. It also updates the service, handler, and store layers to accommodate these changes and adds integration tests to ensure correct functionality.
* **Error Definitions**: Added `ErrorInvalidLimit` and `ErrorInvalidOffset` to handle invalid pagination parameters. (`backend/internal/ou/constants/errorconstants.go`, [backend/internal/ou/constants/errorconstants.goR86-R99](diffhunk://#diff-fdff491fddbde7476f8d278153c07cc15568f67d48435a2e633a6ba5edb98b16R86-R99))
* **Pagination Parsing**: Implemented `parsePaginationParams` to extract and validate `limit` and `offset` from query parameters. (`backend/internal/ou/handler/ouhandler.go`, …

Add pagination support for organization unit listing

---

backend/internal/group/constants/errorconstants.go
backend/internal/group/model/group.go
backend/internal/group/service/groupservice.go
backend/internal/group/store/store.go

This pull request refactors the group management module by centralizing error constants, removing redundant logging, and simplifying code in the `store` package. The changes improve maintainability and reduce duplication across the codebase.
* Moved error constants `ErrGroupNotFound` and `ErrGroupNameConflict` from `backend/internal/group/model/group.go` to `backend/internal/group/constants/errorconstants.go` for better separation of concerns. Updated all references in `groupservice.go` and `store.go` to use the centralized constants. [[1]](diffhunk://#diff-9a59413761c1238217c81a23c820dcb4d682b6c18ce6a3061235dcd7b6b28af2R112-R120) [[2]](diffhunk://#diff-2da7e5d6c9049c160de801c8a9623aebba03a9492083ba66b2481c892b3ff0a5L115-L126) [[3]](diffhunk://#diff-c968c9fcf81977db22a427b042701414eb10548b …

Refactoring group impl

---

backend/internal/ou/handler/ouhandler.go
backend/internal/ou/model/ou.go
backend/internal/ou/service/ouservice.go
backend/internal/ou/store/queries.go
backend/internal/ou/store/store.go
backend/internal/system/services/ouservice.go
tests/integration/ou/model.go
tests/integration/ou/ouapi_test.go

This pull request introduces significant enhancements to the organization unit (OU) management system, focusing on modularizing the code, improving resource listing capabilities, and refining the data model. The most important changes include adding new handlers and service methods for listing resources related to OUs, introducing a generic resource listing function, simplifying the `OrganizationUnit` data model, and updating database queries for better resource management.
* Added handlers in `ouhandler.go` for listing child OUs, users, and groups under an organization unit: `HandleOUChildrenListRequest`, `HandleOUUsersListRequest`, and `HandleOUGroupsListRequest`. These handlers utilize a generic resource listing function.
* Introduced corresponding service methods in `ouservice.go` to …

Introduce ous, users, groups sub paths & remove those returning in the OU GET response

---

Dockerfile
README.md
backend/cmd/server/repository/conf/deployment.yaml

Add docker quick start guide

---

backend/internal/oauth/jwks/model/model.go

$subject
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Fix naming in jwks response

---

backend/internal/ou/constants/errorconstants.go
backend/internal/ou/handler/ouhandler.go
backend/internal/ou/service/ouservice.go
backend/internal/ou/store/queries.go
backend/internal/ou/store/store.go
backend/internal/system/services/ouservice.go
tests/integration/ou/model.go
tests/integration/ou/ou_tree_api_test.go
tests/integration/ou/ouapi_test.go

This pull request introduces significant enhancements to the organization unit (OU) management functionality, including support for hierarchical handle paths, improved error handling, and code refactoring for better maintainability. Key changes include adding new handlers and service methods for operations by handle path, introducing utility functions to reduce code duplication, and updating error codes for consistency.
* **Support for Handle Path Operations**:
- Added new methods to the `OrganizationUnitServiceInterface` for retrieving, updating, and deleting OUs by hierarchical handle paths (`GetOrganizationUnitByPath`, `UpdateOrganizationUnitByPath`, `DeleteOrganizationUnitByPath`).
- Implemented corresponding service logic in `backend/internal/ou/service/ouservice.go`, including …

Introduce GET, PUT, DELETE by handle path for OU API

---

docs/apis/flow.yaml

This pull request updates the flow API definition to enhance the flexibility and clarity of the API schema for handling flow requests and responses. The changes include splitting the `FlowRequest` and `FlowResponse` schemas into more specific subtypes, adding examples for better documentation, and refining property descriptions.

Update flow API definition

---

README.md

Fix curl commands in README

---

frontend/apps/gate/package.json
frontend/pnpm-lock.yaml

Change @oxygen-ui/react  dependency path to **"@oxygen-ui/react": "workspace:*"** in package.json of gate app to fix import errors.

Update oxygen-ui dependency path in gate app

---

backend/internal/oauth/oauth2/authz/authzhandler.go
backend/internal/oauth/oauth2/authz/authzvalidator.go
backend/internal/oauth/oauth2/authz/store/store.go
backend/internal/oauth/oauth2/granthandlers/authorizationcode.go
backend/internal/oauth/oauth2/granthandlers/clientcredentials.go
backend/internal/oauth/oauth2/granthandlers/refreshtoken.go

This pull request refactors the OAuth2 authorization handler and authorization code storage logic to improve modularity, testability, and maintainability. The changes introduce dependency injection for key services in the `AuthorizeHandler`, encapsulate authorization code persistence in a dedicated package with a clear interface, and enhance logging with component names for better traceability.

Refactor OAuth: define struct vars for external service invocations

---

.vscode/launch.json
README.md
start.sh

Add remote debugging capability for Thunder backend using Delve - Issue #290.

Add remote debugging capability

---

backend/internal/executor/attributecollect/attributecollector.go
backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/executor/identify/identifyingexecutor.go
backend/internal/executor/provision/provisioningexecutor.go
backend/internal/executor/smsauth/smsauthexecutor.go
backend/internal/group/service/groupservice.go
backend/internal/user/constants/errorconstants.go
backend/internal/user/handler/userhandler.go
backend/internal/user/model/user.go
backend/internal/user/service/userservice.go
backend/internal/user/store/queries.go
backend/internal/user/store/store.go
tests/integration/flowregistration/model.go
tests/integration/flowregistration/utils.go
tests/integration/user/model.go
tests/integration/user/userapi_test.go

This pull request introduces server-side pagination for the user listing API. It standardizes the user list response format, adds error handling for pagination parameters, and updates the data model and persistence layers to support paginated queries. Additionally, it adjusts integration tests to accommodate the new response structure.
**Pagination and API Response Enhancements:**
* Added pagination support to the user listing endpoint, including parsing `limit` and `offset` query parameters, applying defaults, and returning paginated results. Errors for invalid pagination parameters are now handled and returned in a standardized format. [[1]](diffhunk://#diff-a835c982b85fd7017f2332cf2ed0a2c4297f043cbf59b7ff9ce4764da0b9afbeL74-R118) …

Improve user api to support pagination

---

backend/internal/group/store/queries.go
backend/internal/ou/store/queries.go
backend/internal/user/handler/userhandler.go
backend/internal/user/service/userservice.go
backend/internal/user/store/queries.go
backend/internal/user/store/store.go

This pull request refactors and reorganizes database query definitions and handler/service logic for user, group, and organization unit management in the backend. The main goals are to improve code clarity, maintain consistent query IDs, and ensure logical grouping of queries. It also includes minor functional changes to handler and service implementations.
**Database Query Refactoring and Reorganization**
_Group Queries (`backend/internal/group/store/queries.go`):_
* Reordered and renumbered all group-related query IDs for better logical grouping and consistency. Queries for group listing, creation, update, deletion, member management, and conflict checks now follow a sequential and thematic order.
* Updated the query ID for bulk group existence checks to align with the new numbering …

Reorder user method impl & Reorder query ids in user, group and ou impls

---

README.md

Update readme indentation

---

.github/workflows/issue-chat-notification.yml

Add a git action to trigger chat notification for issues

---

.github/release-drafter.yml
.github/workflows/issue-chat-notification.yml
.github/workflows/pr-label-check.yml
.github/workflows/release.yml

This pull request introduces a improvements to the release workflow and automation for pull requests. The main changes include the addition of a Release Drafter configuration, enhancements to the release workflow to automatically generate and include changelogs, and the introduction of a new workflow to enforce PR label requirements. These updates streamline release management and improve consistency in labeling and changelog generation.
https://github.com/release-drafter/release-drafter
**Release automation and changelog improvements:**
* Added `.github/release-drafter.yml` to configure automatic changelog generation for releases, including templates for naming, categorizing changes, and excluding certain labels.
* Enhanced `.github/workflows/release.yml` to generate changelogs using …

Add release drafter workflow

---

tests/integration/identity/oauth2/authz/authz_test.go
tests/integration/identity/oauth2/authz/utils.go

Add initial set of authorization code grant-based integration tests.

Add authorization code grant integration tests

---

backend/internal/system/database/utils/querybuilder.go
backend/internal/user/constants/errorconstants.go
backend/internal/user/handler/userhandler.go
backend/internal/user/service/userservice.go
backend/internal/userschema/constants/errorconstants.go
backend/internal/userschema/service/userschemaservice.go
tests/integration/userschema/model.go
tests/integration/userschema/user_tree_validation_test.go
tests/integration/userschema/user_uniqueness_test.go
tests/integration/userschema/user_validation_edge_cases_test.go
tests/integration/userschema/user_validation_test.go

This pull request introduces schema-based validation and uniqueness checks for user attributes, ensuring that user data conforms to defined schemas and that unique constraints are enforced. The changes span both the user service and user schema service, adding new validation logic and updating error handling for conflicts.
**User attribute validation and uniqueness enforcement:**
* Added `ValidateUser` and `ValidateUserUniqueness` methods to `UserSchemaServiceInterface` and implemented them in `userschemaservice.go` to validate user attributes against JSON schemas and enforce uniqueness constraints, including nested and array properties. [[1]](diffhunk://#diff-e8d5097d7949db2bec3b45598c2e9bc3d517474d3b7191d7abf1aa7828659938R46-R48) …

Introduce user schema enforcement to the user operations 

---

backend/internal/user/constants/errorconstants.go
backend/internal/user/handler/userhandler.go
backend/internal/user/service/userservice.go
backend/internal/user/store/queries.go
backend/internal/user/store/store.go
backend/tests/mocks/user/servicemock/UserServiceInterface_mock.go
docs/apis/user.yaml
tests/integration/user/user_filter_test.go
tests/integration/user/userapi_test.go

This pull request adds support for filtering user list endpoints using a `filter` query parameter, enabling clients to retrieve users based on specific attribute values. It introduces robust parsing, validation, and sanitization of filter parameters, updates the service and data access layers to handle filters, and ensures error handling for invalid filters. Additionally, the mock interfaces and tests are updated to accommodate these changes.
**API and Handler Enhancements:**
- Added parsing, validation, and sanitization of the `filter` query parameter in user list handlers (`HandleUserListRequest`, `HandleUserListByPathRequest`). Now, filters are extracted, validated, and passed to the service layer. Invalid filters return a client error. …

Add basic filter support for user listing

---

Dockerfile

This PR is to update the Docker image to add user ID and group ID. Previously, an auto generated ID was assigned to the user and the group. With this PR, the user ID and group ID will be explicitly set to 802.
The value 802 was selected to be aligned with the other WSO2 docker images.

Update Docker image to add user ID and group ID

---

.github/workflows/release.yml

Update release workflow to package macOS sample app

---

.github/workflows/release.yml

Disable automatic version update in release workflow

---

.github/release-drafter.yml

Update release-drafter to disable 'other changes'

---

backend/internal/userschema/service/userschemaservice.go
docs/apis/user.yaml
tests/integration/userschema/userschema_api_create_test.go
tests/integration/userschema/userschema_api_delete_test.go
tests/integration/userschema/userschema_api_get_test.go
tests/integration/userschema/userschema_api_update_test.go
tests/integration/userschema/userschema_required_api_test.go

This pull request introduces support for a `required` property in user schema definitions, allowing schema authors to specify which fields are mandatory. The changes span backend validation logic, OpenAPI documentation, and integration tests to ensure correct enforcement and documentation of required fields.
**Backend validation and enforcement:**
- Added support for a `required` boolean property in user schema definitions for string, object, and array types, including validation that the value is a boolean and enforcement during user attribute validation. (`backend/internal/userschema/service/userschemaservice.go` [[1]](diffhunk://#diff-e8d5097d7949db2bec3b45598c2e9bc3d517474d3b7191d7abf1aa7828659938R324) [[2]](diffhunk://#diff-e8d5097d7949db2bec3b45598c2e9bc3d517474d3b7191d7abf1aa7828659 …

Add support to define required attributes in user-schema

---

backend/internal/system/database/provider/dbprovider.go

This pull request refactors the `DBProvider` implementation in `dbprovider.go` to improve client initialization, connection management, and code maintainability. The changes consolidate redundant logic, ensure thread-safe client handling, and streamline graceful shutdown procedures.
**Database client initialization and retrieval:**
- Replaces separate `getIdentityClient` and `getRuntimeClient` methods with a unified `getOrInitClient` function, which uses locking to safely initialize and return database clients as needed. (`backend/internal/system/database/provider/dbprovider.go` [backend/internal/system/database/provider/dbprovider.goR70-R144](diffhunk://#diff-eafa77676b8e2a63143744dd404197f3de724439198248945bfa05481dc51140R70-R144))
- Adds `initializeAllClients` to eagerly initialize …

Refactor dbprovider to reduce code duplication

---

backend/internal/authn/oauth/service.go
backend/internal/authn/oauth/utils.go
backend/internal/executor/githubauth/githubauthexecutor.go
backend/internal/executor/googleauth/googleauthexecutor.go
backend/internal/executor/oauth/oauthexecutor.go
backend/internal/executor/oidcauth/oidcauthexecutor.go
backend/internal/flow/utils/utils.go
backend/internal/idp/errorconstants.go
backend/internal/idp/handler.go
backend/internal/idp/model.go
backend/internal/idp/service.go
backend/internal/idp/store.go
backend/internal/idp/storeconstants.go
backend/internal/system/services/idpservice.go

This pull request refactors the identity provider (IDP) package to consolidate its components under a single `idp` package, improving maintainability and simplifying imports across the codebase. The changes eliminate subpackages like `constants`, `model`, `service`, and `handler`, moving their contents directly into the `idp` package. This results in broad updates to import paths and type references throughout the authentication, executor, and flow layers.
- https://github.com/asgardeo/thunder/issues/432

Refactor the IDP package/ service

---

backend/internal/notification/otpservice.go

Update hash usage

---

backend/internal/authn/oauth/utils.go
backend/internal/flow/utils/utils.go
backend/internal/idp/handler.go
backend/internal/idp/model.go
backend/internal/idp/service.go
backend/internal/idp/store.go
backend/internal/notification/common/model.go
backend/internal/notification/message/customclient.go
backend/internal/notification/message/twilioclient.go
backend/internal/notification/message/vonageclient.go
backend/internal/notification/messagehandler.go
backend/internal/notification/store.go
backend/internal/notification/utils.go
backend/internal/system/cmodels/property.go

This PR addresses the issue where `Property` struct exposes the `Value` field, allowing direct access to encrypted values and bypassing `GetValue()`. It encapsulates fields, adds constructors and getters, introduces a `PropertyDTO` for API communication, and moves encryption into the constructor. These changes enforce controlled access, preserve API compatibility, and improve error handling for encryption/decryption.
- #448

Improve secret properties handling
