asgardeo/thunder

cmd/server/main.go
internal/application/service/applicationservice.go
internal/application/utils/utils.go
internal/identity/oauth2/token/tokenhandler.go
internal/services/service.go
internal/system/database/client/dbclient.go
internal/utils/httputil.go

This pull request includes a variety of changes aimed at improving code readability, fixing inconsistencies, and removing unused functionality. The most important changes include renaming methods and variables for clarity, replacing shorthand variable declarations with explicit ones, removing unused functions, and handling potential errors in JSON encoding.
* Renamed `initMultiPlexer` to `initMultiplexer` to fix a typo and ensure consistency in naming throughout the codebase. (`cmd/server/main.go`) [[1]](diffhunk://#diff-53cd25fc908d5e63cc8675afbd4ff0910572a985a7cfec27f4460eb674f3b98eL50-R50) [[2]](diffhunk://#diff-53cd25fc908d5e63cc8675afbd4ff0910572a985a7cfec27f4460eb674f3b98eL104-R105)
* Updated log message in `startServer` to improve clarity by changing "Starting Asgardeo Thunder..." …

Minor refactoring

---

internal/identity/oauth2/granthandlers/clientcredentials.go
tests/integration/identity/oauth2/token/token_test.go
tests/integration/run_tests.go

This pull request refactors and enhances the integration tests for the OAuth2 client credentials grant, improves error handling, and introduces minor updates to test execution. The most significant changes include restructuring test cases for better modularity, adding negative test cases, and improving the test command for better output visibility.
* Refactored `TestClientCredentialsGrant` into modular test functions (`runClientCredentialsTestCase`, `TestClientCredentialsGrantWithHeaderCredentials`, `TestClientCredentialsGrantWithBodyCredentials`, and `TestClientCredentialsGrantNegativeCases`) to improve readability and maintainability. These changes include the addition of parameterized test cases for various scenarios, such as valid, invalid, and missing credentials. …

Add more integration tests for client credentials grant

---

internal/identity/oauth2/model/parameter.go
internal/identity/oauth2/token/tokenhandler.go
internal/identity/session/model/sessiondata.go
internal/identity/session/store/sessiondatastore.go

This pull request defines new models for OAuth2 and session management. Below is a breakdown of the most important changes:
* [`internal/identity/session/model/sessiondata.go`](diffhunk://#diff-faf8035cca137084ce280e8715ee35617c80701d754220e92321f589a4619677R1-R40): Added `SessionData` struct to encapsulate OAuth2 parameters, authenticated user details, and authentication time. Introduced a temporary `AuthenticatedUser` struct for user details, with a note to relocate it later.
* [`internal/identity/session/store/sessiondatastore.go`](diffhunk://#diff-ef1b22cdb51e6e64d732c452dc9fd01a424555283ad22c6ed312e821fefa77b2R1-R127): Implemented `SessionDataStore`, a thread-safe in-memory store for managing session data with methods to add, retrieve, and clear sessions. Introduced a singleton …

Add initial session data store implementation

---

dbscripts/thunderdb/sqlite.sql
tests/integration/application/applicationapi_test.go

This pull request includes changes to the database schema, sample data, and integration tests to update the structure and behavior of the `SP_APP` table and related configurations. The most important changes include replacing the `VERSION` column with a `DESCRIPTION` column in the `SP_APP` table, updating sample data to reflect this change, and modifying integration tests to align with the updated schema and OAuth configuration.
* [`dbscripts/thunderdb/sqlite.sql`](diffhunk://#diff-0d30131a01d4802d5bfe51a4be6f8adfcc1443277b7d538e6714443a881e60f9L4-R6): Replaced the `VERSION` column in the `SP_APP` table with a `DESCRIPTION` column to provide a more descriptive field for applications.
* [`dbscripts/thunderdb/sqlite.sql`](diffhunk://#diff-0d30131a01d4802d5bfe51a4be6f8adfcc1443277b7d538e67144 …

Fix application api tests

---

README.md
cmd/server/repository/conf/deployment.yaml
internal/services/authnservice.go
internal/system/config/config.go
tests/integration/resources/deployment.yaml

This pull request refactors the configuration structure for user credentials by replacing the `oauth.auth_credentials` section with a new `user_store.default_user` section. The changes affect configuration files, documentation, and related code to align with the new structure.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L69-R76): Updated the documentation to reflect the new `user_store.default_user` section for configuring credentials, replacing the old `oauth.auth_credentials` section. Example credentials were also updated.
* [`cmd/server/repository/conf/deployment.yaml`](diffhunk://#diff-e2d5d08a43b2b2ff5b57e20a8127235faddb793b97936ea20140f894afa8d48fL17-R20): Replaced the `oauth.auth_credentials` section with the …

Add default user config

---

backend/internal/system/database/provider/dbprovider.go
backend/scripts/init_script.sh
tests/integration/testutils/testutils.go

This pull request refactors the `init_script.sh` and updates its usage in the integration test utility. The changes improve flexibility by introducing named arguments, adding support for optional database recreation, and enhancing readability and maintainability.
* Refactored `scripts/init_script.sh` to use named arguments (`-db`, `-type`, `-name`, etc.) instead of positional arguments, improving clarity and usability.
* Added support for optional database recreation via the `-recreate` flag, allowing users to drop and recreate databases if needed.
* Updated validation logic to ensure required arguments are provided, with specific checks for PostgreSQL parameters.
* Modified `RunInitScript` in `tests/integration/testutils/testutils.go` to use the updated `init_script.sh` with named …

Fix init script to accept named arguments and recreate DBs during tests

---

backend/internal/application/service/applicationservice.go
backend/internal/application/store/store.go
backend/internal/oauth/oauth2/authz/codepersistence.go
backend/internal/oauth/scope/validator/scopevalidator.go
backend/internal/system/database/client/dbclient.go
backend/internal/system/server/serveroperation.go

This pull request refactors database client methods to improve clarity and functionality by replacing the `ExecuteQuery` method with two distinct methods: `Query` for SELECT operations and `Execute` for non-SELECT operations. It also updates all relevant function calls across the codebase to use these new methods.
* Introduced `Query` and `Execute` methods in `DBClientInterface` to separate SELECT queries from non-SELECT operations. Updated their implementations in `backend/internal/system/database/client/dbclient.go`. (`[[1]](diffhunk://#diff-848200784aa14c671eb132579fae6350a6d79894b8eef5c7d7be69f373eb2754L35-R41)`, `[[2]](diffhunk://#diff-848200784aa14c671eb132579fae6350a6d79894b8eef5c7d7be69f373eb2754L52-R58)`, `[[3]](diffhunk://#diff-848200784aa14c671eb132579fae6350a6d79894b8eef5c7d7be …

Introduce execute function to DBClient

---

samples/api/postman/user.json

This pull request adds a new Postman collection file, `samples/api/postman/user.json`, to define and document API endpoints for user-related operations. The collection includes endpoints for standard CRUD operations on users.
* Added a new Postman collection file, `samples/api/postman/user.json`, which includes the following endpoints:
- **List Users**: A `GET` endpoint to retrieve a list of users.
- **Create User**: A `POST` endpoint to create a new user, with a JSON body containing user details such as organization ID, type, attributes (age, roles, address), etc.
- **Get User**: A `GET` endpoint to retrieve details of a specific user by their ID.
- **Update User**: A `PUT` endpoint to update an existing user's details, including their organization ID, type, and attributes.
- **Delete …

Add sample postman collection for initial user api

---

backend/cmd/server/repository/conf/deployment.yaml
build.sh

This pull request introduces changes to improve certificate management and enhance the build script's structure. The most important updates include fixing a file extension issue in the deployment configuration, refactoring the build script to dynamically ensure certificates for multiple directories, and adding new directory variables for better organization.
* [`backend/cmd/server/repository/conf/deployment.yaml`](diffhunk://#diff-fb7b89dae773382f1ed4977c550448c9098477d2f747a254a3345d923c5e0eb8L10-R10): Corrected the certificate file extension from `.crt` to `.cert` to align with standard naming conventions.
* [`build.sh`](diffhunk://#diff-4d2a8eefdf2a9783512a35da4dc7676a66404b6f3826a8af9aad038722da6823L85-R132): Refactored the `run` function to delegate certificate generation to a new …

Generate gate app's and sample app's keys and certs during the build

---

README.md
package.json

This pull request renames the `oauth-sample` script to `sample` for consistency and updates the corresponding references in the documentation.
Script and documentation updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L9-R9): Renamed the `oauth-sample` script to `sample` to simplify the naming convention.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L141-R141): Updated the command example to use `pnpm sample` instead of `pnpm oauth-sample` to reflect the script name change.

Make the sample app run command shorter

---

samples/apps/oauth/package.json
samples/apps/oauth/vite.config.ts

This pull request introduces a new `start` script to the `package.json` file and updates the Vite configuration to include a `preview` section. These changes streamline the development workflow and enhance consistency in the preview environment.
* [`samples/apps/oauth/package.json`](diffhunk://#diff-9cd0f80d59179651a39b4b35eac82fd2abe6cb2d8d6429140d54b7e29407c88aR9): Added a `start` script that combines building the project (`tsc -b` and `vite build`) and starting the preview server (`vite preview`).
* [`samples/apps/oauth/vite.config.ts`](diffhunk://#diff-4553e5b48255db876bb802c6f7db56b4387aa7f3924b47db4c746bf3ce116033R34-R37): Added a `preview` configuration block to specify the `port` and `host`, ensuring consistent settings for the preview server.

Add the ability to run the sample app without the dev mode

---

package.json

This pull request includes a minor update to the `package.json` file. The change removes the `"run": "make run"` script, streamlining the script definitions.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L7): Removed the `"run": "make run"` script from the `scripts` section, as it may no longer be necessary or has been replaced by other commands.

Remove pnpm run

---

.github/workflows/pr-builder.yml
Makefile
build.sh

This pull request introduces changes to make the build process architecture-aware by adding support for specifying the target architecture (`ARCH`) across the build system. The most important changes include updates to the `Makefile`, `build.sh` script, and GitHub Actions workflow to incorporate the `ARCH` parameter.
* **`Makefile`:** Updated all relevant targets (`clean`, `build`, `test`, `run`) to pass the `ARCH` parameter to `build.sh`, ensuring architecture-specific builds. (`[MakefileL41-R50](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L41-R50)`)
* **`build.sh`:**
* Modified the `GOARCH` variable to default to `arm64` if no architecture is specified, allowing flexibility in specifying the target architecture. …

Make thunder binary target architecture configurable

---

README.md

This pull request updates the `README.md` file to fix formatting issues in several `curl` command examples by removing unnecessary trailing commas and adjusting the closing of JSON payloads. These changes ensure the examples are syntactically correct and easier to follow.
Formatting fixes in `README.md`:
* Removed unnecessary trailing commas and adjusted the closing of JSON payloads in multiple `curl` command examples to ensure proper syntax. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L98-R99) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L136-R135) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L187-R186) [[4]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1 …

Fix flow initiation curl command & refactoring

---

.github/workflows/release.yml
build.sh
tests/integration/testutils/testutils.go

This pull request introduces a restructuring of the build and distribution process, focusing on the separation of output directories and improving artifact packaging. Key changes include the introduction of a dedicated `dist` directory for distribution artifacts, updates to workflows and scripts to accommodate this change, and enhancements to cleanup and packaging logic.

Add dist directory for packaging and rename sample distribution

---

backend/internal/executor/authassert/authassertexecutor.go
backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/executor/githubauth/githubauthexecutor.go
backend/internal/executor/googleauth/googleauthexecutor.go
backend/internal/executor/oidcauth/oidcauthexecutor.go
backend/internal/executor/oidcauth/utils/utils.go
backend/internal/flow/engine/flowengine.go
backend/internal/flow/flowservice.go
backend/internal/flow/model/executor.go
backend/internal/flow/model/flowmodel.go
backend/internal/flow/model/node.go

This pull request refactors the flow execution context across multiple authentication executors and the flow engine, replacing `FlowContext` with `NodeContext` or `EngineContext` as appropriate. The changes aim to streamline context handling and improve data encapsulation for individual nodes and the overall flow execution.

Refactor FlowContext into EngineContext and NodeContext

---

backend/cmd/server/repository/resources/graphs/auth_flow_config_github.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_google.json
backend/internal/executor/authassert/authassertexecutor.go
backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/executor/githubauth/githubauthexecutor.go
backend/internal/executor/googleauth/googleauthexecutor.go
backend/internal/executor/oauth/model/model.go
backend/internal/executor/oauth/oauthexecutor.go
backend/internal/executor/oauth/utils/utils.go
backend/internal/executor/oidcauth/constants.go
backend/internal/executor/oidcauth/oidcauthexecutor.go
backend/internal/flow/constants/constants.go
backend/internal/flow/engine/flowengine.go
backend/internal/flow/flowservice.go
backend/internal/flow/handler/flowexechandler.go
backend/internal/flow/model/executor.go
backend/internal/flow/model/flowmodel.go
backend/internal/flow/model/node.go
backend/internal/flow/utils/utils.go
samples/apps/oauth/src/pages/LoginPage.tsx

This pull request introduces significant updates to the authentication executors, focusing on improving error handling and refining the response structure. The changes include replacing generic error messages with detailed failure reasons, ensuring consistent handling of authentication failures, and modifying method signatures to return errors explicitly where applicable. Additionally, the `ExecutorResponse` initialization has been simplified across multiple executors.
- With this fix we assume any error returned from a executor/ node as a server error and failures returned in the response body as client errors.
- Also this PR fixes the issue of not able to silently execute an executor when required inputs are present in the initial request.
- Also the existing OIDCAuthExecutor is …

Refactor the flow model with proper status handling and executor hierarchy

---

backend/internal/system/healthcheck/handler/healthcheckhandler.go
backend/internal/system/services/healthcheckservice.go

This pull request corrects a typo in the method name `HandleRedinessRequest` by renaming it to `HandleReadinessRequest` across the codebase. The changes ensure consistency and accuracy in naming conventions.
* Renamed the method `HandleRedinessRequest` to `HandleReadinessRequest` in the `HealthCheckHandler` implementation to fix a spelling error. (`backend/internal/system/healthcheck/handler/healthcheckhandler.go`)
* Updated the usage of `HandleRedinessRequest` to `HandleReadinessRequest` in the route registration for the health check service. (`backend/internal/system/services/healthcheckservice.go`)

Fix typo in the handler method name

---

backend/internal/executor/authassert/authassertexecutor.go
backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/executor/githubauth/githubauthexecutor.go
backend/internal/executor/googleauth/googleauthexecutor.go
backend/internal/executor/oauth/oauthexecutor.go
backend/internal/executor/oidcauth/oidcauthexecutor.go
backend/internal/flow/model/executor.go

This pull request refactors multiple executor implementations to centralize and simplify the handling of required input data. The changes replace custom logic for validating and appending required inputs with reusable methods from the `flowmodel.Executor` class. Additionally, default input data is now passed explicitly during executor initialization, improving consistency and maintainability.

Refactor the executor input data handling

---

backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_google.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_google_github.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_or_google.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_github.json
backend/internal/flow/constants/constants.go
backend/internal/flow/constants/errorconstants.go
backend/internal/flow/engine/flowengine.go
backend/internal/flow/flowservice.go
backend/internal/flow/handler/flowexechandler.go
backend/internal/flow/model/decisionnode.go
backend/internal/flow/model/flowmodel.go
backend/internal/flow/model/graph.go
backend/internal/flow/model/node.go
backend/internal/flow/model/taskexecutionnode.go
backend/internal/flow/utils/utils.go
backend/internal/system/utils/httputil.go

This pull request introduces the decision node support for the flow engine. Key changes include the addition of a `DecisionNode` type, updates to the flow graph structure, and modifications to the flow engine's execution logic to support decision nodes and user actions.
* Introduces a new `auth_flow_config_basic_or_google` auth flow definition (json) to support login with Username/Password or Google login.
* Added a new `DecisionNode` type to represent nodes that make decisions based on user actions or input, including logic for handling triggered actions and prompting users when no action is taken.
* Updated the flow graph structure to support multiple next nodes (`NextNodeIDList`) and previous nodes (`PreviousNodeIDList`) for improved flexibility in flow transitions.
* Enhanced the flow …

Add support for decision nodes

---

backend/cmd/server/repository/resources/graphs/auth_flow_config_basic.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_google.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_google_github.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_github.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_google.json
backend/internal/flow/constants/constants.go
backend/internal/flow/engine/flowengine.go
backend/internal/flow/jsonmodel/model.go
backend/internal/flow/model/graph.go
backend/internal/flow/utils/utils.go

This pull request modifies the graph definition by transitioning from the edge-based structure to a node-based `nextNodes` structure. It also introduces a new `GraphType` to categorize graph types and updates the flow engine to accommodate these structural changes.
* Replaced the `Edges` structure with a `NextNodes` property in `NodeDefinition`, simplifying the representation of graph connections.
* Updated graph definitions (`auth_flow_config_*.json`) to use `nextNodes` instead of `edges`, removing the `edges` section entirely.
* Introduced a `GraphType` type and a constant `GraphTypeAuthentication` to categorize graphs.
* Added a `type` field to `GraphDefinition` and `_type` to the `Graph` struct to support the new graph type.
* Replaced `GetStartNodeID` with `GetStartNode` in the …

Modify graph definition from the edge-based structure to a node-based structure

---

backend/cmd/server/repository/resources/graphs/auth_flow_config_basic.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_google.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_google_github.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_with_prompt.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_github.json
backend/cmd/server/repository/resources/graphs/auth_flow_config_google.json
backend/internal/flow/jsonmodel/model.go
backend/internal/flow/utils/utils.go

This pull request refactors the naming of the `nextNodes` field to `next` across JSON configuration files and backend code. This change ensures consistency and simplifies the field name for better readability and maintainability.

Rename next node key

---

backend/cmd/server/repository/resources/graphs/auth_flow_config_basic.json

This pull request includes a small change to the `auth_flow_config_basic.json` file. The change removes the `firstName` field from the configuration, which was previously optional.

Removing optional fields from the basic auth login

---

backend/cmd/server/repository/resources/graphs/auth_flow_config_basic_google_github_sms.json
backend/internal/executor/attributecollect/attributecollector.go
backend/internal/executor/authassert/authassertexecutor.go
backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/executor/oauth/oauthexecutor.go
backend/internal/executor/oidcauth/oidcauthexecutor.go
backend/internal/executor/smsauth/smsauthexecutor.go
backend/internal/flow/model/executor.go
backend/internal/notification/message/service/clientservice.go

This pull request introduces significant updates to the authentication flow configuration and executor logic, focusing on improving user identification and input handling. Key changes include replacing the `username` attribute with `userID` and `mobileNumber` for better flexibility, centralizing user ID resolution logic, and enhancing the SMS OTP authentication flow.
* Replaced `mobile_prompt_username` with `prompt_mobile` and updated its input attribute from `username` to `mobileNumber` in the `auth_flow_config_basic_google_github_sms.json` file. This aligns the configuration with the new user identification approach.
* Introduced a new `GetUserIDFromContext` method across executors (`AttributeCollector`, `AuthAssertExecutor`, `BasicAuthExecutor`, `OAuthExecutor`, `OIDCAuthExecutor`, …

Improve sms OTP executor with having userID as a prerequisite

---

backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/executor/smsauth/smsauthexecutor.go
backend/internal/outboundauth/basicauth/basicauthenticator.go
backend/internal/user/service/userservice.go
backend/internal/user/store/store.go

This pull request refactors the user identification logic across multiple components to improve flexibility and security. The primary change replaces the use of individual attribute-based identification with a more generic filter-based approach, allowing for multiple attributes to be used in user lookups. Additionally, sensitive data handling has been improved by introducing a utility to mask sensitive values in logs.
* Updated the `UserServiceInterface` in `backend/internal/user/service/userservice.go` to replace the `IdentityUser(attrName, attrValue string)` method with `IdentifyUser(filters map[string]interface{})` for more flexible user identification.
* Refactored the `IdentifyUser` implementation in `backend/internal/user/service/userservice.go` to use a `filters` map instead of …

Improve IdentifyUser to filter based on multiple attributes

---

docs/apis/group.yaml
docs/apis/ou.yaml

This pull request introduces two new OpenAPI specifications for managing groups and organization units. These APIs define endpoints for CRUD operations, including listing, creating, updating, and deleting entities, along with their associated schemas and examples.
* Added `docs/apis/group.yaml` to define the Group Management API for handling groups. It includes endpoints for listing, creating, retrieving, updating, and deleting groups, with support for parent-child relationships and user associations.
* Added `docs/apis/ou.yaml` to define the Organization Unit Management API for managing organizational units. It includes similar CRUD operations, with hierarchical relationships and associations with groups and users.

Add group & organization unit API specs

---

backend/internal/system/server/serveroperation.go
backend/internal/system/services/applicationservice.go
backend/internal/system/services/authnservice.go
backend/internal/system/services/authorizationservice.go
backend/internal/system/services/flowexecutionservice.go
backend/internal/system/services/healthcheckservice.go
backend/internal/system/services/idpservice.go
backend/internal/system/services/notificationsenderservice.go
backend/internal/system/services/service.go
backend/internal/system/services/tokenservice.go
backend/internal/system/services/userservice.go

This pull requests moves the existing server operations functionality to a new `ServerOperationService`. The changes refactor all available API services to use this new service, improving code modularity and reducing duplication. 
This allows to inject mock services to the API and server operations services.
Additionally, the unused abstract service structure has been removed to simplify the codebase.

Refactor the server ops and API services to allow injecting providers

---

backend/cmd/server/main.go
backend/internal/system/config/config.go

This pull request introduces support for running the server in HTTP-only mode, alongside the existing TLS-enabled mode. The changes include adding a configuration option for HTTP-only mode, implementing a new function to start an HTTP server, and updating the server initialization logic to handle both modes.
* [`backend/internal/system/config/config.go`](diffhunk://#diff-70ef91d44215280f2234659532a25f97986a90f9f6e8e798167394efdfe0bacbR35): Added a new `HTTPOnly` field to the `ServerConfig` struct to allow configuration of HTTP-only mode.
* [`backend/cmd/server/main.go`](diffhunk://#diff-2074e8c0103565d3d16275fe3ce1e98a4a567b910968e57c8410292d526ac408R57-R63): Updated the `main` function to check the `HTTPOnly` configuration and start the server without TLS if enabled.
* …

Add support to run without tls

---

backend/internal/executor/attributecollect/attributecollector.go
backend/internal/executor/authassert/authassertexecutor.go
backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/executor/githubauth/githubauthexecutor.go
backend/internal/executor/googleauth/googleauthexecutor.go
backend/internal/executor/oauth/oauthexecutor.go
backend/internal/executor/oidcauth/oidcauthexecutor.go
backend/internal/executor/smsauth/smsauthexecutor.go
backend/internal/flow/model/executor.go
backend/internal/flow/utils/utils.go

This pull request ensures that executors utilize the already existing executor properties map to configure the executor properties.
Currently this will be utilized in SMS OTP flow to configure the notification `senderName`.

Update executors to utilize executor properties

---

backend/internal/executor/attributecollect/attributecollector.go
backend/internal/executor/authassert/authassertexecutor.go
backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/executor/githubauth/githubauthexecutor.go
backend/internal/executor/googleauth/constants.go
backend/internal/executor/googleauth/googleauthexecutor.go
backend/internal/executor/identify/identifyingexecutor.go
backend/internal/executor/oauth/oauthexecutor.go
backend/internal/executor/oidcauth/constants.go
backend/internal/executor/oidcauth/oidcauthexecutor.go
backend/internal/executor/smsauth/smsauthexecutor.go

This pull request introduces enhancements to the executor framework by implementing user identification capabilities across various executors. A new `IdentifyingExecutor` is added to centralize user identification logic, and existing executors are updated to utilize this functionality. Additionally, error handling and user resolution mechanisms are improved for better reliability.
> :warning: **Note:** 
> With this change for federated login scenarios, always a unique user should be created in the local system with the matching unique identifier from the federated IDPs (`sub` claim for google/ oidc or `id` claim for github). Otherwise the authentication will fail with user not found error.
* [`backend/internal/executor/identify/identifyingexecutor.go`]: Added a new `IdentifyingExecutor` …

Add user validation for federated authenticators with identifying executor

---

backend/cmd/server/repository/resources/graphs/registration_flow_config_basic_google_github.json
backend/internal/executor/githubauth/githubauthexecutor.go
backend/internal/executor/oauth/oauthexecutor.go
backend/internal/executor/oidcauth/oidcauthexecutor.go
backend/internal/executor/provision/provisioningexecutor.go
backend/internal/flow/engine/flowengine.go

This pull request refactors the OAuth and OIDC auth executors (i.e. Google and Github) to support user registration through the `ProvisioningExecutor`. Below is a summary of the most important changes grouped by theme.
* Added a JSON configuration file for registration with basic and social options: `registration_flow_config_basic_google_github.json`.
* Refactored `OAuthExecutor`, `OIDCAuthExecutor` and `GithubOAuthExecutor` to handle registration flows by checking `FlowType` and allowing user registration if the user does not exist.
* Adjusted logic in the `ProcessAuthFlowResponse` method to avoid authentication failure for registration flows when the user is not authenticated.
* Allow retrieving user attributes from the authenticated user during registration flows.
- …

Add user registration support for federated auth executors

---

backend/cmd/server/repository/resources/graphs/registration_flow_config_basic_google_github.json
backend/internal/executor/provision/provisioningexecutor.go

This pull request fixes the issue of not provisioning user password during registration flows by adding support for storing non-identifying attributes during user creation. 
* **Configuration file update**: Removed the `inputData` section from `registration_flow_config_basic_google_github.json`, simplifying the task execution configuration for the provisioning step.
* **New helper method**: Added `appendNonIdentifyingAttributes` method in `ProvisioningExecutor` to handle non-identifying attributes, such as passwords, by checking both `UserInputData` and `RuntimeData`.
* **Integration of helper method**: Updated the `Execute` method in `ProvisioningExecutor` to call `appendNonIdentifyingAttributes` before creating the user in the store, ensuring non-identifying attributes are included.
- …

Fix password storing issue in user provisioning flow

---

docs/apis/ou.yaml

This pull request updates the OpenAPI specification in `docs/apis/ou.yaml` by simplifying the documentation for the "List organization units" endpoint. The changes remove query parameters and examples related to filtering by parent organization unit, streamlining the API documentation.
* Removed the `parent` query parameter from the "List organization units" endpoint, which was used to filter by immediate children of a specified organization unit.
* Consolidated multiple examples into a single `example` for the response, removing the distinction between root organization units and nested organization units. [[1]](diffhunk://#diff-e36ca15f70fb14f6ea92bfffc234f4937f72dfbc23f3e0fc05fac0d4cb9b84a1L46-R37) [[2]](diffhunk://#diff-e36ca15f70fb14f6ea92bfffc234f4937f72dfbc23f3e0fc05fac0d4cb9b84a1L6 …

Update OU API

---

backend/internal/oauth/oauth2/authz/codepersistence.go
backend/internal/oauth/oauth2/authz/constants/constants.go
backend/internal/oauth/oauth2/granthandlers/authorizationcode.go
backend/internal/oauth/oauth2/granthandlers/clientcredentials.go
backend/internal/oauth/oauth2/granthandlers/granthandler.go
backend/internal/oauth/oauth2/token/tokenhandler.go
backend/internal/system/services/tokenservice.go

This pull request refactors the OAuth 2.0 grant handling logic by moving some validations done at `HandleGrant` to the `ValidateGrant` function. Additionally this fixed the runtime issue for invalid codes in token requests.
* [`backend/internal/oauth/oauth2/granthandlers/granthandler.go`](diffhunk://#diff-59f7aa51179d30b9686236cd01ed54e74570d8e08090f9bf7c7c71131d7c8498L29-R31): Updated the `GrantHandler` interface to include the `oauthApp` parameter in both `ValidateGrant` and `HandleGrant` methods, enabling grant validation to incorporate application-specific logic.
* [`backend/internal/oauth/oauth2/authz/codepersistence.go`](diffhunk://#diff-2a6a5c76f53cb2d677962489c7062478f1f81ac754b5a49afae8e58fc3b3ec67R109-R111): Added a check to return an error when no authorization code is found, …

Refactor grant handler validations

---

backend/internal/group/constants/errorconstants.go
backend/internal/group/handler/grouphandler.go
backend/internal/group/model/group.go
backend/internal/group/service/groupservice.go
backend/internal/group/store/queries.go
backend/internal/group/store/store.go
tests/integration/group/groupapi_test.go
tests/integration/group/model.go

This pull request introduces pagination support for the group listing API, along with validation for pagination parameters and comprehensive test coverage. The changes span multiple files, including the addition of new error constants, updated service methods, and integration tests for the new functionality.
* [`backend/internal/group/handler/grouphandler.go`](diffhunk://#diff-cb150916dc3c5f592f9048103e47b3a410c1addf6b3cfc9a16be7fc77d03776cR53-R65): Added logic to parse and validate `limit` and `offset` query parameters, with a default limit of 30. Updated the `HandleGroupListRequest` method to support pagination and return paginated responses. [[1]](diffhunk://#diff-cb150916dc3c5f592f9048103e47b3a410c1addf6b3cfc9a16be7fc77d03776cR53-R65) …

Improve Group listing to support pagination

---

backend/internal/ou/service/ouservice.go
backend/internal/ou/store/queries.go
backend/internal/ou/store/store.go

This pull request simplifies the handling of organization unit (OU) name and handle conflict checks by removing redundant methods and queries. The changes streamline the codebase and improve maintainability by consolidating conflict-checking logic.
* Removed conditional logic in `UpdateOrganizationUnit` to use a single method for checking name and handle conflicts, regardless of whether the operation is an update or a new creation. (`backend/internal/ou/service/ouservice.go`) [[1]](diffhunk://#diff-a3f9ac4d3a59e9804a4ff0c0ebdcfc4233de31b9ee092cad8f3ff4117f303430L217-L229) [[2]](diffhunk://#diff-a3f9ac4d3a59e9804a4ff0c0ebdcfc4233de31b9ee092cad8f3ff4117f303430L238-L250)
* Deleted redundant queries for checking name and handle conflicts during updates, as they are no longer required. …

Introduce name, handle conflict check in OU impl

---

backend/internal/ou/model/ou.go
backend/internal/ou/store/queries.go
backend/internal/ou/store/store.go
tests/integration/ou/ouapi_test.go

This pull request refactors the handling of organization units by focusing on root-level units and removing the `Parent` field from the `OrganizationUnitBasic` struct. The changes simplify the queries and data structures to better align with the new requirements, while also updating related integration tests.
* Removed the `Parent` field from the `OrganizationUnitBasic` struct in `ou.go`. (`[backend/internal/ou/model/ou.goL28](diffhunk://#diff-4d4890f9a2e4d14375477c5efa691745371d6f826272f079611b463004a16c38L28)`)
* Renamed and updated queries in `queries.go` to focus on root-level organization units by adding a `WHERE PARENT_ID IS NULL` condition. (`[backend/internal/ou/store/queries.goL30-R40](diffhunk://#diff-15dd481b97543fd8035acb0e3b9d79dfc31b41348dab761b4230dcc78704422dL30-R40)`)
* …

Update OU Listing to retrieve only the root OUs

---

backend/internal/ou/model/ou.go
backend/internal/ou/service/ouservice.go
backend/internal/ou/store/queries.go
backend/internal/ou/store/store.go

This pull request removes the handling of sub-organization units from the `OrganizationUnit` model and related services, simplifying the codebase. The most important changes include the removal of the `OrganizationUnits` field from the `OrganizationUnitBasic` struct, the deletion of methods and logic for retrieving sub-organization units, and the cleanup of unused fields in related functions.
* [`backend/internal/ou/model/ou.go`](diffhunk://#diff-4d4890f9a2e4d14375477c5efa691745371d6f826272f079611b463004a16c38L28): Removed the `OrganizationUnits` field from the `OrganizationUnitBasic` struct, as sub-organization units are no longer part of the model.
* [`backend/internal/ou/service/ouservice.go`](diffhunk://#diff-a3f9ac4d3a59e9804a4ff0c0ebdcfc4233de31b9ee092cad8f3ff4117f303430L80-L95): …

Exclude child attribute from the OU list response

---

backend/internal/system/log/accesslog.go
backend/internal/system/log/accesslog_test.go
backend/internal/system/log/log.go
backend/internal/system/log/log_test.go

- This PR refactors the HTTP access logging by extracting it from `log.go` file into a dedicated `accesslog.go` file.
- Also enhances the access logs by including **elapsed time** while being aligned with the Apache's Combined Log Format (CLF).

Restructure Access Log and Add Elapsed Time

---

backend/internal/group/handler/grouphandler.go
backend/internal/group/service/groupservice.go
backend/internal/ou/handler/ouhandler.go
backend/internal/ou/service/ouservice.go
backend/internal/system/constants/serverconstants.go
backend/internal/user/handler/userhandler.go
backend/internal/user/service/userservice.go

This pull request standardizes pagination limit constants across the codebase by introducing `DefaultPaginationLimit` and `MaxPaginationLimit` in `serverconstants.go`, and updating all relevant handlers and services to use these shared values. This improves maintainability and consistency for pagination logic in group, organization unit, and user management operations.
**Pagination Limit Standardization**
* Added `DefaultPaginationLimit` and `MaxPaginationLimit` constants to `backend/internal/system/constants/serverconstants.go` for centralized pagination configuration.
* Updated group, organization unit, and user handlers (`grouphandler.go`, `ouhandler.go`, `userhandler.go`) to use `serverconst.DefaultPaginationLimit` instead of local `limitDefault` constants when the pagination limit is …

Introduce system constants for pagination page default and limit.

---

backend/internal/cert/certservice.go
backend/internal/cert/constants/errorconstants.go
backend/internal/cert/store/cachedbackedstore.go
backend/internal/cert/store/store.go

This pull request introduces a caching layer for certificate management and improves error handling and validation in certificate CRUD operations. The main changes include switching to a cached certificate store, adding new error types, and enforcing stricter validation when creating and updating certificates to prevent duplicate entries and reference changes.
**Caching and Store Refactoring:**
* Introduced a new `CachedBackedCertificateStoreInterface` and its implementation in `backend/internal/cert/store/cachedbackedstore.go`, providing caching for certificate retrieval, creation, update, and deletion operations. This improves performance by reducing direct store access and ensures cache consistency.
* Updated `CertificateService` in `backend/internal/cert/certservice.go` to use …

Integrate caching to the cert service

---

frontend/pnpm-lock.yaml

Update gate app to use the latest version of pnpm, which was downgraded in: https://github.com/asgardeo/thunder/pull/281.

Update gate app to use latest pnpm version

---

backend/internal/application/model/application.go
backend/internal/application/store/store.go

This pull request updates how the `is_registration_flow_enabled` field is handled in the application models and database logic to ensure consistent serialization and deserialization. The main changes focus on always including this field in API responses (removing `omitempty`), and improving database handling to support both string and byte representations.
This is done to fix the errors on postgreSQL databases.

Fix application queries for postgres

---

backend/internal/flow/constants/errorconstants.go
backend/internal/flow/flowexecservice.go

This pull request introduces an additional error handling mechanism for the registration flow in the backend service. The main change is the introduction of a new error type to handle cases where the registration flow is disabled for an application, and its integration into the flow graph retrieval logic.

Add registration flow enabled validation to the flow service

---

.github/actions/setup-node/action.yml
.github/workflows/release.yml

This pull request introduces a reusable GitHub Action for setting up the Node.js environment and integrates it into the release workflow. The goal is to improve consistency and maintainability of Node.js setup across CI jobs.
**Reusable GitHub Action for Node.js setup:**
* Added a new composite action in `.github/actions/setup-node/action.yml` to standardize Node.js environment setup, using `actions/setup-node@v4` with a configurable version and node cache.
**Release workflow improvements:**
* Updated `.github/workflows/release.yml` to use the new setup-node action for Node.js environment setup before updating sample app versions, ensuring a consistent environment for subsequent steps.

Add release step to setup node environment

---

build.sh
tests/integration/main.go

This pull request improves how tests are executed by preferring the use of `gotestsum` for both unit and integration tests if it is available, while still falling back to `go test` when necessary. This enhances test output readability and consistency across environments.
**Test execution improvements:**
* Updated the `test_unit` function in `build.sh` to check for `gotestsum` and use it for running unit tests if available, otherwise defaults to `go test`.
* Modified the `runTests` function in `tests/integration/main.go` to similarly prefer `gotestsum` for integration tests, falling back to `go test` if `gotestsum` is not installed.

Add support for run tests using gotestsum

---

.github/workflows/release.yml

This pull request adds automation to the release workflow to streamline version management after a release. The workflow now automatically calculates the next development version, updates relevant version files, and commits these changes directly to the main branch.
**Release version automation:**
* Added a step to calculate the next minor development version by parsing the current release version and incrementing the minor component.
* Updated the `version.txt` file with the new version for the next development iteration.
**Sample apps version update:**
* Automated the update of `package.json` files for the main sample app and its server to reflect the new version.
**Commit and push automation:**
* Added a step to commit and push all version updates to the main branch, ensuring the …

Fix release workflow to bump product version

---

backend/internal/system/server/serveroperation.go

This pull request refactors the logic for handling cases where no allowed origins are found in the `getAllowedOrigins` method. The main change is to set `originList` to an empty slice instead of returning early, ensuring consistent flow and caching behavior.
Error handling and control flow improvements:
* Refactored the handling of empty results in `getAllowedOrigins` to set `originList` to an empty slice and continue execution, rather than returning early. This ensures that the empty list is still cached, improving consistency and avoiding potential cache misses.

Improve caching in 'allowed origins'

---

.github/workflows/release.yml

This pull request makes a small update to the release workflow by changing the section header emoji in the release notes from a recycling symbol to a shuffle symbol.
- Changed the "What's Changed" section header emoji in `.github/workflows/release.yml` from ♻️ to 🔀 to better represent the nature of the changes.

Update release change list heading emoji

---

backend/internal/authn/dto/dto.go
backend/internal/executor/attributecollect/attributecollector.go
backend/internal/executor/authassert/authassertexecutor.go
backend/internal/executor/basicauth/basicauthexecutor.go
backend/internal/executor/githubauth/githubauthexecutor.go
backend/internal/executor/oauth/oauthexecutor.go
backend/internal/executor/oidcauth/oidcauthexecutor.go
backend/internal/executor/provision/provisioningexecutor.go
backend/internal/executor/smsauth/smsauthexecutor.go
backend/internal/flow/constants/errorconstants.go
backend/internal/flow/engine/flowengine.go
backend/internal/flow/flowexecservice.go
backend/internal/flow/model/flowmodel.go
backend/internal/flow/store/model.go
backend/internal/oauth/session/store/sessiondatastore_test.go
backend/internal/system/utils/sliceutil.go

Should be rebased and merged after https://github.com/asgardeo/thunder/pull/351 & https://github.com/asgardeo/thunder/pull/353
This pull request improves the auth assertion JWT token issuance logic to use the token configurations configured for the authenticating application. With this following changes will be introduced to the auth assertion.
- Utilize application's issuer and validity period
- Will include user attributes configured for the application in the jwt token
In order to support the above requirement, this pull request also adds the Application struct to the flow contexts (`EngineContext` and `NodeContext`). With this, the server requires to retrieve and add the application to the context on each flow execution request.
- https://github.com/asgardeo/thunder/issues/345
- …

Improve auth assertion to use application token configurations

---

.github/release-drafter.yml
.github/workflows/release.yml

This pull request fixes the release drafter and incorporate the changelog into the release description. Additionally this PR also introduces a new `prerelease` input parameter to allow marking releases as pre-releases, and updated the release creation step to use this parameter.
- https://github.com/asgardeo/thunder/issues/379

Fix release drafter and add pre-release input

---

install/helm/.helmignore
install/helm/Chart.yaml
install/helm/README.md
install/helm/conf/deployment.yaml
install/helm/templates/_helpers.tpl
install/helm/templates/config-map.yaml
install/helm/templates/hpa.yaml
install/helm/templates/ingress.yaml
install/helm/templates/pdb.yaml
install/helm/templates/rbac.yaml
install/helm/templates/service-account.yaml
install/helm/templates/service.yaml
install/helm/templates/thunder-deployment.yaml
install/helm/values.yaml

This PR introduces a Helm chart to deploy Thunder in a Kubernetes environments.
This PR includes;
- Deployment definition for deploying Thunder pods
- Configurable deployment parameters including replica count, rolling update strategy, and security contexts
- Pre-configured health checks (startup, liveness, and readiness probes)
- Service definition for exposing Thunder API
- Ingress configuration for external access
- Horizontal Pod Autoscaler for automatic scaling
- Pod Disruption Budget for high availability during cluster maintenance
- RBAC and Service Account setup for proper Kubernetes permissions
- ConfigMap for deployment configurations

Add Helm Chart for Thunder Kubernetes Deployment

---

README.md

This pull request updates the documentation to reflect the minimum required Go version for the project.
Documentation update:
* Updated the prerequisite in `README.md` to require Go 1.25+ instead of Go 1.24+.

Update README to indicate Go version requirement as 1.25

---

backend/cmd/server/main.go
backend/internal/cert/systemcertservice.go
backend/internal/oauth/jwks/constants/constants.go
backend/internal/oauth/jwks/service.go
backend/internal/oauth/jwks/service_test.go
backend/internal/system/config/runtimeconfig.go
backend/internal/system/jwt/service.go
backend/internal/system/jwt/service_test.go
backend/tests/mocks/certmock/SystemCertificateServiceInterface_mock.go

This pull request refactors how TLS certificate configuration and Key ID (kid) management are handled throughout the backend. The main change is the introduction of a centralized `CertConfig` struct in the runtime config, which stores both the TLS configuration and the certificate kid. This approach replaces previous patterns of repeatedly fetching or calculating the kid and TLS config through file reads, streamlining access and reducing redundant operations. The JWKS and JWT services, as well as their tests, are updated to use this new pattern, and error handling is improved and made more explicit.

Fix redundant file reads on tls config and cert kid handling

---

install/helm/README.md
install/helm/templates/thunder-deployment.yaml
install/helm/values.yaml

This PR is to parameterize readOnlyRootFilesystem with default as false to facilitate sqlite DB.
The file system is required to have write access if SQLite DB is used as the DB stores data in the file system.

Parameterize readOnlyRootFilesystem and update readme

---

backend/cmd/server/main.go
backend/cmd/server/repository/conf/deployment.yaml
backend/cmd/server/repository/resources/conf/default.json
backend/internal/application/store/store.go
backend/internal/cert/store/store.go
backend/internal/flow/store/store.go
backend/internal/group/store/store.go
backend/internal/idp/store/store.go
backend/internal/notification/message/store/store.go
backend/internal/oauth/oauth2/authz/store/store.go
backend/internal/oauth/oauth2/authz/store/store_test.go
backend/internal/ou/store/store.go
backend/internal/system/config/config.go
backend/internal/system/database/provider/dbclient.go
backend/internal/system/database/provider/dbclient_test.go
backend/internal/system/database/provider/dbprovider.go
backend/internal/system/healthcheck/service/healthcheckservice.go
backend/internal/system/healthcheck/service/healthcheckservice_test.go
backend/internal/user/store/store.go
backend/internal/userschema/store/store.go
backend/tests/mocks/database/providermock/DBProviderInterface_mock.go
install/helm/values.yaml

1. Improve to use a singleton instance of DBProvider that returns identity and runtime DBClients with configured connection pooling.
2. Stop closing DBClients at each store-level and close only during shutting down of server.
- https://github.com/asgardeo/thunder/issues/324

Centralizing DB Client creation and closing & Introduce database connection pooling

---

backend/internal/authn/common/model.go
backend/internal/authn/errorconstants.go
backend/internal/authn/google/service.go
backend/internal/authn/handler.go
backend/internal/authn/model.go
backend/internal/authn/oidc/service.go
backend/internal/authn/service.go
backend/internal/system/managers/servicemanager.go
backend/internal/system/services/authenticationservice.go
docs/apis/authentication.yaml

This pull request introduces 3 new authentication API endpoints for authenticating users against a federated IDP. With this support will be added to authenticate with a Google OIDC, Github OAuth and any other standard OAuth/ OIDC federated identity provider.
Additionally, this improves the ID token validation logic for Google authentication.
The most important changes are:
**Authentication API Layer Implementation:**
* Added a new `AuthenticationHandler` in `backend/internal/authn/handler.go` to handle authentication API requests for Google, GitHub, and standard OAuth flows, including request parsing, response formatting, and error handling.
* Introduced request/response and DTO models for authentication flows in `backend/internal/authn/model.go`, standardizing the data structures used …

Add federated IDP authentication API and service implementation
